"""Generate Rust outline data from Bazel-declared font inputs and output paths."""
import argparse
from pathlib import Path

from fontTools.pens.basePen import BasePen
from fontTools.ttLib import TTFont


SYMBOLS = {
    "TREBLE": 0xe050, "BASS": 0xe062, "BLACK": 0xe0a4, "HALF": 0xe0a3,
    "WHOLE": 0xe0a2, "SHARP": 0xe262, "FLAT": 0xe260, "NATURAL": 0xe261,
    "DOUBLE_SHARP": 0xe263, "DOUBLE_FLAT": 0xe264, "REST_QUARTER": 0xe4e5,
    "REST_HALF": 0xe4e4, "REST_WHOLE": 0xe4e3, "REST_EIGHTH": 0xe4e6,
    "FLAG_UP": 0xe240, "FLAG_DOWN": 0xe241, "FOUR": 0xe084,
}
CHARACTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789#()+/- "


class Flatten(BasePen):
    """Flatten each curve into 16 segments for the shared vector renderer."""

    def __init__(self, glyphs):
        super().__init__(glyphs)
        self.contours = []

    def _moveTo(self, point):
        self.contours.append([point])

    def _lineTo(self, point):
        self.contours[-1].append(point)

    def _closePath(self):
        pass

    def _curveToOne(self, a, b, c):
        start = self._getCurrentPoint()
        for step in range(1, 17):
            t = step / 16
            self._lineTo(tuple(
                (1-t)**3*start[k] + 3*(1-t)**2*t*a[k] + 3*(1-t)*t*t*b[k] + t**3*c[k]
                for k in [0, 1]
            ))

    def _qCurveToOne(self, a, b):
        start = self._getCurrentPoint()
        for step in range(1, 17):
            t = step / 16
            self._lineTo(tuple(
                (1-t)**2*start[k] + 2*(1-t)*t*a[k] + t*t*b[k] for k in [0, 1]
            ))


def outline(glyphs, glyph_name, units, precision):
    pen = Flatten(glyphs)
    glyphs[glyph_name].draw(pen)
    contours = []
    for contour in pen.contours:
        points = ','.join(f'({x/units:.{precision}f},{-y/units:.{precision}f})' for x, y in contour)
        contours.append('&[' + points + ']')
    return '&[' + ','.join(contours) + ']'


def music_source(font):
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    output = [
        '// Generated MIDI Keys Symbols: outlines derived from Bravura (OFL-1.1).',
        '// Copyright Steinberg Media Technologies GmbH. See assets/BRAVURA-LICENSE.txt.',
        '// Generated by Bazel using assets/extract_music_glyphs.py.',
        '#![allow(clippy::approx_constant)]',
    ]
    for name, code in SYMBOLS.items():
        output += ['#[rustfmt::skip]', f'pub const {name}: &[&[(f64,f64)]] = {outline(glyphs, cmap[code], 250, 4)};']
    return '\n'.join(output) + '\n'


def lettering_source(font):
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    units = font['head'].unitsPerEm
    output = [
        '// Generated MIDI Keys Chord Lettering, derived from Liberation Sans 2.1.5 (OFL-1.1).',
        '// Copyright Google Corporation (2010), Red Hat, Inc. (2012).',
        '// See assets/LIBERATION-LICENSE.txt and assets/NOTATION.md.',
        '#![allow(clippy::approx_constant)]',
    ]
    for char in CHARACTERS:
        output += ['#[rustfmt::skip]', f'const C{ord(char)}: &[&[(f64,f64)]] = {outline(glyphs, cmap[ord(char)], units, 5)};']
    output += ['#[rustfmt::skip]', "pub fn glyph(ch: char) -> Option<(f64, &'static [&'static [(f64, f64)]])> {", '    match ch {']
    for char in CHARACTERS:
        advance = font['hmtx'][cmap[ord(char)]][0] / units
        output.append(f"        '{char}' => Some(({advance:.5f}, C{ord(char)})),")
    output += ['        _ => None,', '    }', '}']
    return '\n'.join(output) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ['music_font', 'lettering_font', 'music_output', 'lettering_output']:
        parser.add_argument(name, type=Path)
    args = parser.parse_args()
    with TTFont(args.music_font) as font:
        args.music_output.write_text(music_source(font), encoding='utf-8')
    with TTFont(args.lettering_font) as font:
        args.lettering_output.write_text(lettering_source(font), encoding='utf-8')


if __name__ == '__main__':
    main()
