load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "spritesheet",
    srcs = [
        "pack.go",
        "rembg.go",
        "spritesheet.go",
    ],
    importpath = "github.com/juanique/monorepo/salsa/tools/spritegen/spritesheet",
    visibility = ["//visibility:public"],
)

go_test(
    name = "spritesheet_test",
    srcs = ["spritesheet_test.go"],
    data = [
        "//salsa/tools/spritegen:rembg_tool",
        "//salsa/tools/spritegen/testing:testdata",
    ],
    size = "large",
    deps = [
        ":spritesheet",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@io_bazel_rules_go//go/tools/bazel",
    ],
)
