load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rs//rs:rust_test.bzl", "rust_test")

rust_library(
    name = "sprout",
    srcs = glob(["src/**/*.rs"]),
    edition = "2021",
    visibility = ["//visibility:public"],
    deps = ["@crates//:gpui"],
)

rust_test(
    name = "sprout_test",
    crate = ":sprout",
    edition = "2021",
)
